import { ImageSourcePropType } from "react-native";

export interface ProductSubItem {
    id: number;
    name: string;
    price: number;
    volume: number;
    img: ImageSourcePropType;
    pieces: number;
    productdetails: string;
    nutritions: string;
    review: string;
    rating: number;
    quantity?: number;
}

export interface ProductItem {
    id: number;
    label?: string;
    title: string;
    image: ImageSourcePropType;
    data: ProductSubItem[];
}

export const ProductListData: ProductItem[] = [

    {
        id: 1,
        title: 'Beverages',
        image: require('../assets/productListImg/category1.png'),
        data: [
            {
                id: 1,
                name: 'Diet Coke',
                price: 1.99,
                volume: 580,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Classic low-calorie cola with crisp flavor.",
                nutritions: "Calories: 1 kcal per 100ml. Contains caffeine.",
                review: "Refreshing and perfect for diet-conscious drinkers.",
                rating: 2,
            },
            {
                id: 2,
                name: 'Sprite Can',
                price: 1.2,
                volume: 520,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Lemon-lime flavored soda with a crisp and clean taste.",
                nutritions: "Calories: 140 kcal per can. Caffeine-free.",
                review: "Light and refreshing, great for all occasions.",
                rating: 4,
            },
            {
                id: 3,
                name: 'Apple & Grape Juice',
                price: 1.8,
                volume: 300,
                img: require('../assets/coke3.png'),
                pieces: 1,
                productdetails: "A sweet blend of apple and grape juices.",
                nutritions: "Calories: 50 kcal per 100ml. Rich in vitamins A & C.",
                review: "Natural and tasty, perfect for kids.",
                rating: 3,
            },
            {
                id: 4,
                name: 'Orange Juice',
                price: 3.0,
                volume: 500,
                img: require('../assets/coke4.png'),
                pieces: 1,
                productdetails: "Freshly squeezed orange juice with natural pulp.",
                nutritions: "Calories: 45 kcal per 100ml. High in Vitamin C.",
                review: "Tangy and refreshing, a healthy choice.",
                rating: 5,
            },
            {
                id: 5,
                name: 'Coca Cola Can',
                price: 3.0,
                volume: 330,
                img: require('../assets/coke5.png'),
                pieces: 1,
                productdetails: "Classic Coca Cola with original flavor.",
                nutritions: "Calories: 140 kcal per can. Contains caffeine.",
                review: "Iconic soda loved worldwide.",
                rating: 1,
            },
            {
                id: 6,
                name: 'Pepsi Can',
                price: 3.0,
                volume: 250,
                img: require('../assets/coke6.png'),
                pieces: 1,
                productdetails: "Pepsi soda can with bold and refreshing taste.",
                nutritions: "Calories: 150 kcal per can. Contains caffeine.",
                review: "Great alternative to cola lovers.",
                rating: 4,
            },
            {
                id: 7,
                name: 'Mountain Dew',
                price: 2.5,
                volume: 355,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Citrus-flavored carbonated drink with high energy.",
                nutritions: "Calories: 170 kcal per bottle. Contains caffeine.",
                review: "Perfect for an energy boost.",
                rating: 5,
            },
            {
                id: 8,
                name: '7 Up',
                price: 1.2,
                volume: 355,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Lemon-lime soda with a crisp, clean taste.",
                nutritions: "Calories: 140 kcal per can. Caffeine-free.",
                review: "Refreshing and light soda option.",
                rating: 3,
            },

        ]
    },
    {
        id: 2,
        title: 'Fresh Fruits & Vegetable',
        label: 'Exclusive Offer',
        image: require('../assets/productListImg/category2.png'),
        data: [
            {
                id: 1,
                name: "apple",
                pieces: 7,
                price: 4.99,
                img: require('../assets/apple.png'),
                volume: 500,
                productdetails: "This is a healthy and fresh fruit.\nPerfect for daily nutrition needs.",
                nutritions: "Calories: 100 kcal per 100g. Rich in fiber and vitamin C.",
                review: "Loved by most customers for its crispness and natural sweetness.",
                rating: 5,
                quantity: 1
            },
            {
                id: 2,
                name: "banana",
                pieces: 7,
                price: 4.99,
                volume: 500,
                img: require('../assets/banana.png'),
                productdetails: "This is a healthy and fresh fruit.\nPerfect for daily nutrition needs.",
                nutritions: "Calories: 100 kcal per 100g. Rich in fiber and vitamin C.",
                review: "Popular for its creamy texture and quick energy boost.",
                rating: 4,
                quantity: 1
            },
            {
                id: 3,
                name: "orange",
                pieces: 7,
                price: 4.99,
                volume: 500,
                img: require('../assets/orange.png'),
                productdetails: "This is a healthy and fresh fruit.\nPerfect for daily nutrition needs.",
                nutritions: "Calories: 100 kcal per 100g. Rich in fiber and vitamin C.",
                review: "Praised for its juicy segments and refreshing citrus flavor.",
                rating: 3,
                quantity: 1
            },
            {
                id: 4,
                name: "pine apple",
                pieces: 7,
                price: 4.99,
                volume: 250,
                img: require('../assets/pineapple.png'),
                productdetails: "This is a healthy and fresh fruit.\nPerfect for daily nutrition needs.",
                nutritions: "Calories: 100 kcal per 100g. Rich in fiber and vitamin C.",
                review: "Favored for its tropical flavor and excellent digestive properties.",
                rating: 5,
                quantity: 1
            },
        ]
    },
    {
        id: 3,
        title: 'Chickens',
        image: require('../assets/productListImg/category3.png'),
        data: [
            {
                id: 1,
                name: 'Diet Coke',
                price: 1.99,
                volume: 580,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Classic low-calorie cola with crisp flavor.",
                nutritions: "Calories: 1 kcal per 100ml. Contains caffeine.",
                review: "Refreshing and perfect for diet-conscious drinkers.",
                rating: 4,
            },
            {
                id: 2,
                name: 'Sprite Can',
                price: 1.2,
                volume: 520,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Lemon-lime flavored soda with a crisp and clean taste.",
                nutritions: "Calories: 140 kcal per can. Caffeine-free.",
                review: "Light and refreshing, great for all occasions.",
                rating: 4,
            },
            {
                id: 3,
                name: 'Apple & Grape Juice',
                price: 1.8,
                volume: 300,
                img: require('../assets/coke3.png'),
                pieces: 1,
                productdetails: "A sweet blend of apple and grape juices.",
                nutritions: "Calories: 50 kcal per 100ml. Rich in vitamins A & C.",
                review: "Natural and tasty, perfect for kids.",
                rating: 5,
            },
            {
                id: 4,
                name: 'Orange Juice',
                price: 3.0,
                volume: 500,
                img: require('../assets/coke4.png'),
                pieces: 1,
                productdetails: "Freshly squeezed orange juice with natural pulp.",
                nutritions: "Calories: 45 kcal per 100ml. High in Vitamin C.",
                review: "Tangy and refreshing, a healthy choice.",
                rating: 5,
            },
            {
                id: 5,
                name: 'Coca Cola Can',
                price: 3.0,
                volume: 330,
                img: require('../assets/coke5.png'),
                pieces: 1,
                productdetails: "Classic Coca Cola with original flavor.",
                nutritions: "Calories: 140 kcal per can. Contains caffeine.",
                review: "Iconic soda loved worldwide.",
                rating: 4,
            },
            {
                id: 6,
                name: 'Pepsi Can',
                price: 3.0,
                volume: 250,
                img: require('../assets/coke6.png'),
                pieces: 1,
                productdetails: "Pepsi soda can with bold and refreshing taste.",
                nutritions: "Calories: 150 kcal per can. Contains caffeine.",
                review: "Great alternative to cola lovers.",
                rating: 4,
            },
            {
                id: 7,
                name: 'Mountain Dew',
                price: 2.5,
                volume: 355,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Citrus-flavored carbonated drink with high energy.",
                nutritions: "Calories: 170 kcal per bottle. Contains caffeine.",
                review: "Perfect for an energy boost.",
                rating: 4,
            },
            {
                id: 8,
                name: '7 Up',
                price: 1.2,
                volume: 355,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Lemon-lime soda with a crisp, clean taste.",
                nutritions: "Calories: 140 kcal per can. Caffeine-free.",
                review: "Refreshing and light soda option.",
                rating: 4,
            }
        ]
    },
    {
        id: 4,
        title: 'Bakery & Bread',
        image: require('../assets/productListImg/category4.png'),
        data: [

            {
                id: 1,
                name: 'Diet Coke',
                price: 1.99,
                volume: 580,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Classic low-calorie cola with crisp flavor.",
                nutritions: "Calories: 1 kcal per 100ml. Contains caffeine.",
                review: "Refreshing and perfect for diet-conscious drinkers.",
                rating: 4,
            },
            {
                id: 2,
                name: 'Sprite Can',
                price: 1.2,
                volume: 520,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Lemon-lime flavored soda with a crisp and clean taste.",
                nutritions: "Calories: 140 kcal per can. Caffeine-free.",
                review: "Light and refreshing, great for all occasions.",
                rating: 4,
            },
            {
                id: 3,
                name: 'Apple & Grape Juice',
                price: 1.8,
                volume: 300,
                img: require('../assets/coke3.png'),
                pieces: 1,
                productdetails: "A sweet blend of apple and grape juices.",
                nutritions: "Calories: 50 kcal per 100ml. Rich in vitamins A & C.",
                review: "Natural and tasty, perfect for kids.",
                rating: 5,
            },
            {
                id: 4,
                name: 'Orange Juice',
                price: 3.0,
                volume: 500,
                img: require('../assets/coke4.png'),
                pieces: 1,
                productdetails: "Freshly squeezed orange juice with natural pulp.",
                nutritions: "Calories: 45 kcal per 100ml. High in Vitamin C.",
                review: "Tangy and refreshing, a healthy choice.",
                rating: 5,
            },
            {
                id: 5,
                name: 'Coca Cola Can',
                price: 3.0,
                volume: 330,
                img: require('../assets/coke5.png'),
                pieces: 1,
                productdetails: "Classic Coca Cola with original flavor.",
                nutritions: "Calories: 140 kcal per can. Contains caffeine.",
                review: "Iconic soda loved worldwide.",
                rating: 4,
            },
            {
                id: 6,
                name: 'Pepsi Can',
                price: 3.0,
                volume: 250,
                img: require('../assets/coke6.png'),
                pieces: 1,
                productdetails: "Pepsi soda can with bold and refreshing taste.",
                nutritions: "Calories: 150 kcal per can. Contains caffeine.",
                review: "Great alternative to cola lovers.",
                rating: 4,
            },
            {
                id: 7,
                name: 'Mountain Dew',
                price: 2.5,
                volume: 355,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Citrus-flavored carbonated drink with high energy.",
                nutritions: "Calories: 170 kcal per bottle. Contains caffeine.",
                review: "Perfect for an energy boost.",
                rating: 4,
            },
            {
                id: 8,
                name: '7 Up',
                price: 1.2,
                volume: 355,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Lemon-lime soda with a crisp, clean taste.",
                nutritions: "Calories: 140 kcal per can. Caffeine-free.",
                review: "Refreshing and light soda option.",
                rating: 4,
            },
        ]

    },

    // {
    //     id: 5,
    //     title: 'Beverages',
    //     image: require('../assets/productListImg/category5.png'),
    //     data: [
    //         {
    //             id: 1,
    //             name: 'Diet Coke',
    //             price: 1.99,
    //             volume: 580,
    //             img: require('../assets/coke1.png'),
    //             pieces: 1,
    //             productdetails: "Classic low-calorie soda with a crisp, refreshing taste.",
    //             nutritions: "Calories: 1 kcal, Sugar: 0g, Caffeine: 46mg",
    //             review: "Light and refreshing, perfect for calorie-conscious consumers.",
    //             rating: 4.5
    //         },
    //         {
    //             id: 2,
    //             name: 'Sprite Can',
    //             price: 1.2,
    //             volume: 520,
    //             img: require('../assets/coke2.png'),
    //             pieces: 1,
    //             productdetails: "Caffeine-free lemon-lime soda with a bubbly, crisp flavor.",
    //             nutritions: "Calories: 140 kcal, Sugar: 38g, Caffeine: 0mg",
    //             review: "Tastes fresh and lively, great for all ages.",
    //             rating: 4.3
    //         },
    //         {
    //             id: 3,
    //             name: 'Apple & Grape Juice',
    //             price: 1.8,
    //             volume: 300,
    //             img: require('../assets/coke3.png'),
    //             pieces: 1,
    //             productdetails: "Sweet blend of apple and grape juices, no artificial flavors.",
    //             nutritions: "Calories: 120 kcal, Sugar: 26g, Caffeine: 0mg",
    //             review: "Smooth and fruity with natural sweetness.",
    //             rating: 4.6
    //         },
    //         {
    //             id: 4,
    //             name: 'Orange Juice',
    //             price: 3.0,
    //             volume: 500,
    //             img: require('../assets/coke4.png'),
    //             pieces: 1,
    //             productdetails: "Freshly squeezed orange juice packed with Vitamin C.",
    //             nutritions: "Calories: 110 kcal, Sugar: 22g, Caffeine: 0mg",
    //             review: "Zesty and refreshing, perfect for breakfast.",
    //             rating: 4.7
    //         },
    //         {
    //             id: 5,
    //             name: 'Coca Cola Can',
    //             price: 3.0,
    //             volume: 330,
    //             img: require('../assets/coke5.png'),
    //             pieces: 1,
    //             productdetails: "The iconic cola soda known for its classic taste and fizz.",
    //             nutritions: "Calories: 140 kcal, Sugar: 39g, Caffeine: 34mg",
    //             review: "Loved worldwide for its unique flavor and smoothness.",
    //             rating: 4.4
    //         },
    //         {
    //             id: 6,
    //             name: 'Pepsi Can',
    //             price: 3.0,
    //             volume: 250,
    //             img: require('../assets/coke6.png'),
    //             pieces: 1,
    //             productdetails: "Bold and sweet cola soda with a slightly sharper flavor.",
    //             nutritions: "Calories: 150 kcal, Sugar: 41g, Caffeine: 38mg",
    //             review: "Good alternative to classic cola, with a strong fan base.",
    //             rating: 4.2
    //         },
    //         {
    //             id: 7,
    //             name: 'Mountain Dew',
    //             price: 2.5,
    //             volume: 355,
    //             img: require('../assets/coke1.png'),
    //             pieces: 1,
    //             productdetails: "Citrus-flavored soda with a high caffeine content.",
    //             nutritions: "Calories: 170 kcal, Sugar: 46g, Caffeine: 54mg",
    //             review: "Energetic and flavorful, perfect for energy boosts.",
    //             rating: 4.4
    //         },
    //         {
    //             id: 8,
    //             name: '7 Up',
    //             price: 1.2,
    //             volume: 355,
    //             img: require('../assets/coke2.png'),
    //             pieces: 1,
    //             productdetails: "Clear lemon-lime soda, caffeine-free and crisp.",
    //             nutritions: "Calories: 140 kcal, Sugar: 38g, Caffeine: 0mg",
    //             review: "Light and refreshing, great for any occasion.",
    //             rating: 4.2
    //         },

    //     ]
    // },


    // {
    //     id: 6,
    //     title: 'Aryuvedic Beverages',
    //     image: require('../assets/productListImg/category6.png'),
    //     data: [
    //         {
    //             id: 1,
    //             name: 'Diet Coke',
    //             price: 1.99,
    //             volume: 580,
    //             img: require('../assets/coke1.png'),
    //             pieces: 1,
    //             productdetails: "Classic low-calorie soda with a crisp, refreshing taste.",
    //             nutritions: "Calories: 1 kcal, Sugar: 0g, Caffeine: 46mg",
    //             review: "Light and refreshing, perfect for calorie-conscious consumers.",
    //             rating: 4.5
    //         },
    //         {
    //             id: 2,
    //             name: 'Sprite Can',
    //             price: 1.2,
    //             volume: 520,
    //             img: require('../assets/coke2.png'),
    //             pieces: 1,
    //             productdetails: "Caffeine-free lemon-lime soda with a bubbly, crisp flavor.",
    //             nutritions: "Calories: 140 kcal, Sugar: 38g, Caffeine: 0mg",
    //             review: "Tastes fresh and lively, great for all ages.",
    //             rating: 4.3
    //         },
    //         {
    //             id: 3,
    //             name: 'Apple & Grape Juice',
    //             price: 1.8,
    //             volume: 300,
    //             img: require('../assets/coke3.png'),
    //             pieces: 1,
    //             productdetails: "Sweet blend of apple and grape juices, no artificial flavors.",
    //             nutritions: "Calories: 120 kcal, Sugar: 26g, Caffeine: 0mg",
    //             review: "Smooth and fruity with natural sweetness.",
    //             rating: 4.6
    //         },
    //         {
    //             id: 4,
    //             name: 'Orange Juice',
    //             price: 3.0,
    //             volume: 500,
    //             img: require('../assets/coke4.png'),
    //             pieces: 1,
    //             productdetails: "Freshly squeezed orange juice packed with Vitamin C.",
    //             nutritions: "Calories: 110 kcal, Sugar: 22g, Caffeine: 0mg",
    //             review: "Zesty and refreshing, perfect for breakfast.",
    //             rating: 4.7
    //         },
    //         {
    //             id: 5,
    //             name: 'Coca Cola Can',
    //             price: 3.0,
    //             volume: 330,
    //             img: require('../assets/coke5.png'),
    //             pieces: 1,
    //             productdetails: "The iconic cola soda known for its classic taste and fizz.",
    //             nutritions: "Calories: 140 kcal, Sugar: 39g, Caffeine: 34mg",
    //             review: "Loved worldwide for its unique flavor and smoothness.",
    //             rating: 4.4
    //         },
    //         {
    //             id: 6,
    //             name: 'Pepsi Can',
    //             price: 3.0,
    //             volume: 250,
    //             img: require('../assets/coke6.png'),
    //             pieces: 1,
    //             productdetails: "Bold and sweet cola soda with a slightly sharper flavor.",
    //             nutritions: "Calories: 150 kcal, Sugar: 41g, Caffeine: 38mg",
    //             review: "Good alternative to classic cola, with a strong fan base.",
    //             rating: 4.2
    //         },
    //         {
    //             id: 7,
    //             name: 'Mountain Dew',
    //             price: 2.5,
    //             volume: 355,
    //             img: require('../assets/coke1.png'),
    //             pieces: 1,
    //             productdetails: "Citrus-flavored soda with a high caffeine content.",
    //             nutritions: "Calories: 170 kcal, Sugar: 46g, Caffeine: 54mg",
    //             review: "Energetic and flavorful, perfect for energy boosts.",
    //             rating: 4.4
    //         },
    //         {
    //             id: 8,
    //             name: '7 Up',
    //             price: 1.2,
    //             volume: 355,
    //             img: require('../assets/coke2.png'),
    //             pieces: 1,
    //             productdetails: "Clear lemon-lime soda, caffeine-free and crisp.",
    //             nutritions: "Calories: 140 kcal, Sugar: 38g, Caffeine: 0mg",
    //             review: "Light and refreshing, great for any occasion.",
    //             rating: 4.2
    //         },
    //     ]
    // },

    {
        id: 5,
        title: 'Dairy & Eggs',
        image: require('../assets/productListImg/category1.png'),
        data: [
            {
                id: 1,
                name: 'Diet Coke',
                price: 1.99,
                volume: 580,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Classic low-calorie soda, refreshing and light.",
                nutritions: "Calories: 1 kcal, Sugar: 0g, Caffeine: 46mg",
                review: "Perfect for those who want flavor without the calories.",
                rating: 4.5
            },
            {
                id: 2,
                name: 'Sprite Can',
                price: 1.2,
                volume: 520,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Lemon-lime soda, caffeine-free and crisp.",
                nutritions: "Calories: 140 kcal, Sugar: 38g, Caffeine: 0mg",
                review: "Light and zesty, great thirst quencher.",
                rating: 4.3
            },
            {
                id: 3,
                name: 'Apple & Grape Juice',
                price: 1.8,
                volume: 300,
                img: require('../assets/coke3.png'),
                pieces: 1,
                productdetails: "Blend of natural apple and grape juices.",
                nutritions: "Calories: 120 kcal, Sugar: 26g, Caffeine: 0mg",
                review: "Sweet and smooth with real fruit flavor.",
                rating: 4.6
            },
            {
                id: 4,
                name: 'Orange Juice',
                price: 3.0,
                volume: 500,
                img: require('../assets/coke4.png'),
                pieces: 1,
                productdetails: "Freshly squeezed, rich in vitamin C.",
                nutritions: "Calories: 110 kcal, Sugar: 22g, Caffeine: 0mg",
                review: "Bright and fresh, perfect start to the day.",
                rating: 4.7
            },
            {
                id: 5,
                name: 'Coca Cola Can',
                price: 3.0,
                volume: 330,
                img: require('../assets/coke5.png'),
                pieces: 1,
                productdetails: "Famous cola soda with classic taste.",
                nutritions: "Calories: 140 kcal, Sugar: 39g, Caffeine: 34mg",
                review: "Iconic flavor, loved worldwide.",
                rating: 4.4
            },
            {
                id: 6,
                name: 'Pepsi Can',
                price: 3.0,
                volume: 250,
                img: require('../assets/coke6.png'),
                pieces: 1,
                productdetails: "Sweet and bold cola flavor.",
                nutritions: "Calories: 150 kcal, Sugar: 41g, Caffeine: 38mg",
                review: "Good alternative to Coca Cola with distinct taste.",
                rating: 4.2
            },
            {
                id: 7,
                name: 'Mountain Dew',
                price: 2.5,
                volume: 355,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Citrus soda with high caffeine content.",
                nutritions: "Calories: 170 kcal, Sugar: 46g, Caffeine: 54mg",
                review: "Energizing and flavorful.",
                rating: 4.4
            },
            {
                id: 8,
                name: '7 Up',
                price: 1.2,
                volume: 355,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Clear, caffeine-free lemon-lime soda.",
                nutritions: "Calories: 140 kcal, Sugar: 38g, Caffeine: 0mg",
                review: "Refreshing and light.",
                rating: 4.2
            },

        ]
    },
    {
        id: 6,
        title: 'Frash Fruits & Vegetable',
        image: require('../assets/productListImg/category2.png'),
        data: [
            {
                id: 1,
                name: 'Diet Coke',
                price: 1.99,
                volume: 580,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Classic low-calorie soda, refreshing and light.",
                nutritions: "Calories: 1 kcal, Sugar: 0g, Caffeine: 46mg",
                review: "Perfect for those who want flavor without the calories.",
                rating: 4.5
            },
            {
                id: 2,
                name: 'Sprite Can',
                price: 1.2,
                volume: 520,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Lemon-lime soda, caffeine-free and crisp.",
                nutritions: "Calories: 140 kcal, Sugar: 38g, Caffeine: 0mg",
                review: "Light and zesty, great thirst quencher.",
                rating: 4.3
            },
            {
                id: 3,
                name: 'Apple & Grape Juice',
                price: 1.8,
                volume: 300,
                img: require('../assets/coke3.png'),
                pieces: 1,
                productdetails: "Blend of natural apple and grape juices.",
                nutritions: "Calories: 120 kcal, Sugar: 26g, Caffeine: 0mg",
                review: "Sweet and smooth with real fruit flavor.",
                rating: 4.6
            },
            {
                id: 4,
                name: 'Orange Juice',
                price: 3.0,
                volume: 500,
                img: require('../assets/coke4.png'),
                pieces: 1,
                productdetails: "Freshly squeezed, rich in vitamin C.",
                nutritions: "Calories: 110 kcal, Sugar: 22g, Caffeine: 0mg",
                review: "Bright and fresh, perfect start to the day.",
                rating: 4.7
            },
            {
                id: 5,
                name: 'Coca Cola Can',
                price: 3.0,
                volume: 330,
                img: require('../assets/coke5.png'),
                pieces: 1,
                productdetails: "Famous cola soda with classic taste.",
                nutritions: "Calories: 140 kcal, Sugar: 39g, Caffeine: 34mg",
                review: "Iconic flavor, loved worldwide.",
                rating: 4.4
            },
            {
                id: 6,
                name: 'Pepsi Can',
                price: 3.0,
                volume: 250,
                img: require('../assets/coke6.png'),
                pieces: 1,
                productdetails: "Sweet and bold cola flavor.",
                nutritions: "Calories: 150 kcal, Sugar: 41g, Caffeine: 38mg",
                review: "Good alternative to Coca Cola with distinct taste.",
                rating: 4.2
            },
            {
                id: 7,
                name: 'Mountain Dew',
                price: 2.5,
                volume: 355,
                img: require('../assets/coke1.png'),
                pieces: 1,
                productdetails: "Citrus soda with high caffeine content.",
                nutritions: "Calories: 170 kcal, Sugar: 46g, Caffeine: 54mg",
                review: "Energizing and flavorful.",
                rating: 4.4
            },
            {
                id: 8,
                name: '7 Up',
                price: 1.2,
                volume: 355,
                img: require('../assets/coke2.png'),
                pieces: 1,
                productdetails: "Clear, caffeine-free lemon-lime soda.",
                nutritions: "Calories: 140 kcal, Sugar: 38g, Caffeine: 0mg",
                review: "Refreshing and light.",
                rating: 4
            }
        ]
    }

];